### ISSUE TITLE
Youtube videos source url fail 

### ISSUE THREAD

**Issue by Bilal14078** [pepe19000/NgxVideoListPlayer#3]
Hi,

I have installed this package in Angular 12 and playlist is working fine with the urls of videos that you have used in your [demo ](https://pepe19000.github.io/Demo/menu/NgxVideoListPlayer) but its not playing videos when I replaced youtube videos URLs in src attribute.

![image](https://user-images.githubusercontent.com/29977481/136599940-ac4d681c-d484-4ee3-9772-2dc30f6efc9b.png)

can you please help me in sorting this issue ? I have added code snippet as well.
![image](https://user-images.githubusercontent.com/29977481/136600034-bbc87f13-0401-4ef2-a76c-fc9655cbeb2c.png)

Thanks

**Comment by pepe19000** [comment]
Hi Bilal14078,

I have to say with regret, it is impossible with this videoplayer package, because video tag only supports files that are either MP4, WebM and Ogg. Youtube already provides you with an "embed" function on their page which auto generates the iFrame for you.

This package work with video tag and not with iframe.

Your Youtube link is not a videosource. It is a link to a page, where you can see a video.

There is Youtube API, i can do it, but it is complicated, so I did not deal with it.

Summary: please, change your Youtube link to video source link.

Maybe in the future i will add youtube video support. But now, i have no time for it.

**Comment by Bilal14078** [comment]
Hi peter,

Thanks for detailed explanation. I'll try to handle it with another way.

Best Regards,
Bilal Ahmad

**Comment by pepe19000** [comment]
Maybe try to download the video, upload it to a public file server (e.g.: Google Drive)  and link from there

**Comment by Bilal14078** [comment]
Yes player would work this way but in my use case I have to play dynamic
playlists using youtube videos. So I can't save these videos on google
drive etc.

Thanks

**Comment by pepe19000** [comment]
Okay, i understand your problem. 
I will see Youtube API tonight. Maybe i can found a solution for you. If need i modify this package with a youtube play solution :)

**Comment by Bilal14078** [comment]
Alright that would be great if that can happen.

Thanks alot.

**Comment by pepe19000** [comment]
I checked Youtube API.
I started the integration of it successfully and finished it, but i need more time to test it.
Tomorrow night i will update this npm package. Please be patient.

Thank you :)

**Comment by Bilal14078** [comment]
Alright that's great.

**Comment by pepe19000** [comment]
The integration is done. You can update the package to 12.2.4.
Please, read the new install guide and enjoy it :)

If you satisfied with this you can find a donation button in my Demo site. 

Thank you,
Peter

**Comment by Bilal14078** [comment]
Hi,

That's a really good news, I'll update it and let you know.

Thanks a lot

Best Regards,
Bilal Ahmad

**Comment by pepe19000** [comment]
Closed
